import { LanguageModel } from "../ipc_types";

export const PROVIDERS_THAT_SUPPORT_THINKING: (keyof typeof MODEL_OPTIONS)[] = [
  "google",
  "vertex",
  "auto",
];

export interface ModelOption {
  name: string;
  displayName: string;
  description: string;
  dollarSigns?: number;
  temperature?: number;
  tag?: string;
  maxOutputTokens?: number;
  contextWindow?: number;
}

export const MODEL_OPTIONS: Record<string, ModelOption[]> = {
  openai: [
    // https://platform.openai.com/docs/models/gpt-5
    {
      name: "gpt-5",
      displayName: "GPT 5",
      description: "OpenAI's flagship model",
      // Technically it's 128k but OpenAI errors if you set max_tokens instead of max_completion_tokens
      maxOutputTokens: undefined,
      contextWindow: 400_000,
      // Requires temperature to be default value (1)
      temperature: 1,
      dollarSigns: 3,
    },
    // https://platform.openai.com/docs/models/gpt-5-mini
    {
      name: "gpt-5-mini",
      displayName: "GPT 5 Mini",
      description: "OpenAI's lightweight, but intelligent model",
      // Technically it's 128k but OpenAI errors if you set max_tokens instead of max_completion_tokens
      maxOutputTokens: undefined,
      contextWindow: 400_000,
      // Requires temperature to be default value (1)
      temperature: 1,
      dollarSigns: 2,
    },
    // https://platform.openai.com/docs/models/gpt-5-nano
    {
      name: "gpt-5-nano",
      displayName: "GPT 5 Nano",
      description: "Fastest, most cost-efficient version of GPT-5",
      // Technically it's 128k but OpenAI errors if you set max_tokens instead of max_completion_tokens
      maxOutputTokens: undefined,
      contextWindow: 400_000,
      // Requires temperature to be default value (1)
      temperature: 1,
      dollarSigns: 1,
    },
    // https://platform.openai.com/docs/models/o4-mini
    {
      name: "o4-mini",
      displayName: "o4 mini",
      description: "Reasoning model",
      // Technically the max output tokens is 100k, *however* if the user has a lot of input tokens,
      // then setting a high max output token will cause the request to fail because
      // the max output tokens is *included* in the context window limit.
      maxOutputTokens: 32_000,
      contextWindow: 200_000,
      temperature: 0,
      dollarSigns: 2,
    },
  ],
  // https://docs.anthropic.com/en/docs/about-claude/models/all-models#model-comparison-table
  anthropic: [
    {
      name: "claude-sonnet-4-20250514",
      displayName: "Claude 4 Sonnet",
      description: "Excellent coder (note: >200k tokens is very expensive!)",
      // See comment below for Claude 3.7 Sonnet for why we set this to 16k
      maxOutputTokens: 16_000,
      contextWindow: 1_000_000,
      temperature: 0,
      dollarSigns: 5,
    },
    {
      name: "claude-3-7-sonnet-latest",
      displayName: "Claude 3.7 Sonnet",
      description: "Excellent coder",
      // Technically the max output tokens is 64k, *however* if the user has a lot of input tokens,
      // then setting a high max output token will cause the request to fail because
      // the max output tokens is *included* in the context window limit, see:
      // https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking#max-tokens-and-context-window-size-with-extended-thinking
      maxOutputTokens: 16_000,
      contextWindow: 200_000,
      temperature: 0,
      dollarSigns: 4,
    },
    {
      name: "claude-3-5-sonnet-20241022",
      displayName: "Claude 3.5 Sonnet",
      description: "Good coder, excellent at following instructions",
      maxOutputTokens: 8_000,
      contextWindow: 200_000,
      temperature: 0,
      dollarSigns: 4,
    },
    {
      name: "claude-3-5-haiku-20241022",
      displayName: "Claude 3.5 Haiku",
      description: "Lightweight coder",
      maxOutputTokens: 8_000,
      contextWindow: 200_000,
      temperature: 0,
      dollarSigns: 2,
    },
  ],
  google: [
    // https://ai.google.dev/gemini-api/docs/models
    {
      name: "gemini-3.5-flash",
      displayName: "Gemini 3.5 Flash",
      description: "Google's latest fastest model (free tier available)",
      maxOutputTokens: 65_536 - 1,
      contextWindow: 1_048_576,
      temperature: 0,
      dollarSigns: 2,
    },
    // https://ai.google.dev/gemini-api/docs/models
    {
      name: "gemini-3.1-pro-preview",
      displayName: "Gemini 3.1 Pro (preview)",
      description: "Google's latest cutting-edge model (free tier available)",
      maxOutputTokens: 65_536 - 1,
      contextWindow: 1_048_576,
      temperature: 0,
      dollarSigns: 4,
    },
    // https://ai.google.dev/gemini-api/docs/models
    {
      name: "gemini-2.5-pro",
      displayName: "Gemini 2.5 Pro",
      description: "Excellent coding model (free tier available)",
      maxOutputTokens: 65_536 - 1,
      contextWindow: 1_048_576,
      temperature: 0,
      dollarSigns: 3,
    },
    // https://ai.google.dev/gemini-api/docs/models
    {
      name: "gemini-2.5-flash",
      displayName: "Gemini 2.5 Flash",
      description: "Fast, intelligent model (free tier available)",
      maxOutputTokens: 65_536 - 1,
      contextWindow: 1_048_576,
      temperature: 0,
      dollarSigns: 2,
    },
    // https://ai.google.dev/gemini-api/docs/models
    {
      name: "gemini-2.5-flash-lite",
      displayName: "Gemini 2.5 Flash Lite",
      description: "Lightweight fastest Gemini model (free tier available)",
      maxOutputTokens: 65_536 - 1,
      contextWindow: 1_048_576,
      temperature: 0,
      dollarSigns: 1,
    },
    // https://ai.google.dev/gemini-api/docs/models
    {
      name: "gemini-2.0-flash",
      displayName: "Gemini 2.0 Flash",
      description: "Previous generation fast model (free tier available)",
      maxOutputTokens: 65_536 - 1,
      contextWindow: 1_048_576,
      temperature: 0,
      dollarSigns: 1,
    },
  ],
  vertex: [
    {
      name: "gemini-3.5-flash",
      displayName: "Gemini 3.5 Flash",
      description: "Vertex AI - Google's latest fastest model",
      maxOutputTokens: 65_536 - 1,
      contextWindow: 1_048_576,
      temperature: 0,
    },
    {
      name: "gemini-3.1-pro-preview",
      displayName: "Gemini 3.1 Pro (preview)",
      description: "Vertex AI - Google's latest cutting-edge model",
      maxOutputTokens: 65_536 - 1,
      contextWindow: 1_048_576,
      temperature: 0,
    },
    {
      name: "gemini-2.5-pro",
      displayName: "Gemini 2.5 Pro",
      description: "Vertex AI - Excellent coding model",
      maxOutputTokens: 65_536 - 1,
      contextWindow: 1_048_576,
      temperature: 0,
    },
    {
      name: "gemini-2.5-flash",
      displayName: "Gemini 2.5 Flash",
      description: "Vertex AI - Fast and intelligent",
      maxOutputTokens: 65_536 - 1,
      contextWindow: 1_048_576,
      temperature: 0,
    },
    {
      name: "gemini-2.5-flash-lite",
      displayName: "Gemini 2.5 Flash Lite",
      description: "Vertex AI - Lightweight fastest model",
      maxOutputTokens: 65_536 - 1,
      contextWindow: 1_048_576,
      temperature: 0,
    },
    {
      name: "gemini-2.0-flash",
      displayName: "Gemini 2.0 Flash",
      description: "Vertex AI - Previous generation model",
      maxOutputTokens: 65_536 - 1,
      contextWindow: 1_048_576,
      temperature: 0,
    },
  ],
  openrouter: [
    {
      name: "qwen/qwen3-coder:free",
      displayName: "Qwen3 Coder (free)",
      description: "Use for free (data may be used for training)",
      maxOutputTokens: 32_000,
      contextWindow: 262_000,
      temperature: 0,
      dollarSigns: 0,
    },
    // https://openrouter.ai/deepseek/deepseek-chat-v3-0324:free
    {
      name: "deepseek/deepseek-chat-v3.1:free",
      displayName: "DeepSeek v3.1 (free)",
      description: "Use for free (data may be used for training)",
      maxOutputTokens: 32_000,
      contextWindow: 128_000,
      temperature: 0,
      dollarSigns: 0,
    },
    {
      name: "deepseek/deepseek-chat-v3-0324:free",
      displayName: "DeepSeek v3 (free)",
      description: "Use for free (data may be used for training)",
      maxOutputTokens: 32_000,
      contextWindow: 128_000,
      temperature: 0,
      dollarSigns: 0,
    },
    {
      name: "qwen/qwen3-coder",
      displayName: "Qwen3 Coder",
      description: "Qwen's best coding model",
      maxOutputTokens: 32_000,
      contextWindow: 262_000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "deepseek/deepseek-chat-v3.1",
      displayName: "DeepSeek v3.1",
      description: "Strong cost-effective model with optional thinking",
      maxOutputTokens: 32_000,
      contextWindow: 128_000,
      temperature: 0,
      dollarSigns: 2,
    },
    // https://openrouter.ai/moonshotai/kimi-k2
    {
      name: "moonshotai/kimi-k2-0905",
      displayName: "Kimi K2",
      description: "Powerful cost-effective model (updated to 0905)",
      maxOutputTokens: 32_000,
      contextWindow: 256_000,
      temperature: 0,
      dollarSigns: 2,
    },
  ],
  auto: [
    {
      name: "auto",
      displayName: "Auto",
      description: "Automatically selects the best model",
      tag: "Default",
      // These are below Gemini 2.5 Pro & Flash limits
      // which are the ones defaulted to for both regular auto
      // and smart auto.
      maxOutputTokens: 32_000,
      contextWindow: 1_000_000,
      temperature: 0,
    },
    {
      name: "free",
      displayName: "Free (OpenRouter)",
      description: "Selects from one of the free OpenRouter models",
      tag: "Free",
      // These are below Gemini 2.5 Pro & Flash limits
      // which are the ones defaulted to for both regular auto
      // and smart auto.
      maxOutputTokens: 32_000,
      contextWindow: 128_000,
      temperature: 0,
    },
    {
      name: "turbo",
      displayName: "Turbo (Pro)",
      description: "Use very fast open-source frontier models",
      maxOutputTokens: 32_000,
      contextWindow: 256_000,
      temperature: 0,
    },
  ],
  azure: [
    {
      name: "gpt-5",
      displayName: "GPT-5",
      description: "Azure OpenAI GPT-5 model with reasoning capabilities",
      maxOutputTokens: 128_000,
      contextWindow: 400_000,
      temperature: 0,
    },
    {
      name: "gpt-5-mini",
      displayName: "GPT-5 Mini",
      description: "Azure OpenAI GPT-5 Mini model",
      maxOutputTokens: 128_000,
      contextWindow: 400_000,
      temperature: 0,
    },
    {
      name: "gpt-5-nano",
      displayName: "GPT-5 Nano",
      description: "Azure OpenAI GPT-5 Nano model",
      maxOutputTokens: 128_000,
      contextWindow: 400_000,
      temperature: 0,
    },
    {
      name: "gpt-5-chat",
      displayName: "GPT-5 Chat",
      description: "Azure OpenAI GPT-5 Chat model",
      maxOutputTokens: 16_384,
      contextWindow: 128_000,
      temperature: 0,
    },
  ],
  nvidia: [
    {
      name: "abacusai/dracarys-llama-3.1-70b-instruct",
      displayName: "Dracarys Llama 3.1 70B",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "bytedance/seed-oss-36b-instruct",
      displayName: "Seed OSS 36B Instruct",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "deepseek-ai/deepseek-v4-flash",
      displayName: "DeepSeek v4 Flash",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 16384,
      contextWindow: 256000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "deepseek-ai/deepseek-v4-pro",
      displayName: "DeepSeek v4 Pro",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 16384,
      contextWindow: 256000,
      temperature: 0,
      dollarSigns: 3,
    },
    {
      name: "google/codegemma-7b",
      displayName: "CodeGemma 7B",
      description: "Create a chat completion",
      maxOutputTokens: 8192,
      contextWindow: 8192,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "google/gemma-2-2b-it",
      displayName: "Gemma 2 2B IT",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 8192,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "google/gemma-7b",
      displayName: "Gemma 7B",
      description: "Create a chat completion",
      maxOutputTokens: 8192,
      contextWindow: 8192,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "meta/llama2-70b",
      displayName: "Llama 2 70B",
      description: "Create a chat completion",
      maxOutputTokens: 4096,
      contextWindow: 4096,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "meta/llama-3.1-8b-instruct",
      displayName: "Llama 3.1 8B Instruct",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "meta/llama-3.1-70b-instruct",
      displayName: "Llama 3.1 70B Instruct",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "meta/llama-3.2-1b-instruct",
      displayName: "Llama 3.2 1B Instruct",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "meta/llama-3.2-3b-instruct",
      displayName: "Llama 3.2 3B Instruct",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "meta/llama-3.3-70b-instruct",
      displayName: "Llama 3.3 70B Instruct",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "microsoft/phi-4-mini-instruct",
      displayName: "Phi-4 Mini Instruct",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "microsoft/phi-4-mini-flash-reasoning",
      displayName: "Phi-4 Mini Flash Reasoning",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "minimaxai/minimax-m2.5",
      displayName: "MiniMax m2.5",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "minimaxai/minimax-m2.7",
      displayName: "MiniMax m2.7",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "mistralai/mistral-nemotron",
      displayName: "Mistral Nemotron",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "mistralai/mixtral-8x7b-instruct",
      displayName: "Mixtral 8x7B Instruct",
      description: "Create a chat completion",
      maxOutputTokens: 8192,
      contextWindow: 32000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "mistralai/mixtral-8x22b-instruct",
      displayName: "Mixtral 8x22B Instruct",
      description: "Create a chat completion",
      maxOutputTokens: 8192,
      contextWindow: 64000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "moonshotai/kimi-k2-instruct",
      displayName: "Kimi K2 Instruct",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 200000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "moonshotai/kimi-k2-thinking",
      displayName: "Kimi K2 Thinking",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 200000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "nvidia/gliner-pii",
      displayName: "GLiNER PII",
      description: "Extract named entities from text using GLiNER PII model",
      maxOutputTokens: 4096,
      contextWindow: 4096,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "nvidia/llama-3.1-nemoguard-8b-content-safety",
      displayName: "Nemoguard 8B Content Safety",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "nvidia/llama-3.1-nemoguard-8b-topic-control",
      displayName: "Nemoguard 8B Topic Control",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "nvidia/nemotron-3-ultra-550b-a55b",
      displayName: "Nemotron 3 Ultra 550B",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 3,
    },
    {
      name: "nvidia/llama-3.1-nemotron-nano-8b-v1",
      displayName: "Nemotron Nano 8B",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "nvidia/llama-3.1-nemotron-safety-guard-8b-v3",
      displayName: "Nemotron Safety Guard 8B v3",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "nvidia/llama-3.3-nemotron-super-49b-v1",
      displayName: "Nemotron Super 49B v1",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "nvidia/llama-3.3-nemotron-super-49b-v1.5",
      displayName: "Nemotron Super 49B v1.5",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
      displayName: "Nemotron Ultra 253B",
      description: "Create a model response for a given chat",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 3,
    },
    {
      name: "nvidia/nemoguard-jailbreak-detect",
      displayName: "Nemoguard Jailbreak Detect",
      description: "Classify text for jailbreak attempt",
      maxOutputTokens: 4096,
      contextWindow: 4096,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "nvidia/nemotron-3-nano-30b-a3b",
      displayName: "Nemotron 3 Nano 30B",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "nvidia/nemotron-3-super-120b-a12b",
      displayName: "Nemotron 3 Super 120B",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "nvidia/nemotron-content-safety-reasoning-4b",
      displayName: "Nemotron Content Safety 4B",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 4096,
      contextWindow: 32000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "nvidia/nemotron-mini-4b-instruct",
      displayName: "Nemotron Mini 4B Instruct",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 4096,
      contextWindow: 32000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "nvidia/nvidia-nemotron-nano-9b-v2",
      displayName: "Nemotron Nano 9B v2",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 4096,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "nvidia/riva-translate-4b-instruct-v1_1",
      displayName: "Riva Translate 4B Instruct",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 4096,
      contextWindow: 4096,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "nvidia/usdcode",
      displayName: "USDCode",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 4096,
      contextWindow: 4096,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "openai/gpt-oss-20b",
      displayName: "GPT OSS 20B",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "openai/gpt-oss-120b",
      displayName: "GPT OSS 120B",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 3,
    },
    {
      name: "qwen/qwen3-5-122b-a10b",
      displayName: "Qwen 3.5 122B",
      description: "Request response from the model",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "qwen/qwen3-next-80b-a3b-instruct",
      displayName: "Qwen 3 Next 80B Instruct",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "qwen/qwen3-next-80b-a3b-thinking",
      displayName: "Qwen 3 Next 80B Thinking",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "qwen/qwq-32b",
      displayName: "QwQ 32B",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "sarvamai/sarvam-m",
      displayName: "Sarvam M",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 4096,
      contextWindow: 8192,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "stepfun-ai/step-3-5-flash",
      displayName: "Step 3.5 Flash",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "stockmark/stockmark-2-100b-instruct",
      displayName: "Stockmark 2 100B Instruct",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "upstage/solar-10.7b-instruct",
      displayName: "Solar 10.7B Instruct",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 4096,
      contextWindow: 4096,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "z-ai/glm4.7",
      displayName: "GLM 4.7",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "z-ai/glm5.1",
      displayName: "GLM 5.1",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 0,
      dollarSigns: 2,
    },
    {
      name: "thinkingmachines/inkling",
      displayName: "Thinking Machines Inkling",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 1,
      topP: 0.95,
      dollarSigns: 2,
    },
    {
      name: "poolside/laguna-xs-2.1",
      displayName: "Poolside Laguna XS 2.1",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 1,
      topP: 0.95,
      dollarSigns: 2,
    },
    {
      name: "z-ai/glm-5.2",
      displayName: "GLM 5.2",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 16384,
      contextWindow: 128000,
      temperature: 1,
      topP: 1,
      dollarSigns: 3,
    },
    {
      name: "minimaxai/minimax-m3",
      displayName: "MiniMax M3",
      description: "Creates a model response for the given chat conversation",
      maxOutputTokens: 8192,
      contextWindow: 128000,
      temperature: 1,
      topP: 0.95,
      dollarSigns: 2,
    },
  ],
  xai: [
    // https://docs.x.ai/docs/models
    {
      name: "grok-code-fast-1",
      displayName: "Grok Code Fast",
      description: "Fast coding model",
      maxOutputTokens: 32_000,
      contextWindow: 256_000,
      temperature: 0,
      dollarSigns: 1,
    },
    {
      name: "grok-4",
      displayName: "Grok 4",
      description: "Most capable coding model",
      maxOutputTokens: 32_000,
      contextWindow: 256_000,
      temperature: 0,
      dollarSigns: 4,
    },
    {
      name: "grok-3",
      displayName: "Grok 3",
      description: "Powerful coding model",
      maxOutputTokens: 32_000,
      contextWindow: 131_072,
      temperature: 0,
      dollarSigns: 4,
    },
  ],
  bedrock: [
    {
      name: "us.anthropic.claude-sonnet-4-20250514-v1:0",
      displayName: "Claude 4 Sonnet",
      description: "Excellent coder (note: >200k tokens is very expensive!)",
      maxOutputTokens: 16_000,
      contextWindow: 1_000_000,
      temperature: 0,
    },
    {
      name: "us.anthropic.claude-3-7-sonnet-20250219-v1:0",
      displayName: "Claude 3.7 Sonnet",
      description: "Excellent coder",
      maxOutputTokens: 16_000,
      contextWindow: 200_000,
      temperature: 0,
    },
    {
      name: "us.anthropic.claude-3-5-sonnet-20241022-v2:0",
      displayName: "Claude 3.5 Sonnet",
      description: "Good coder, excellent at following instructions",
      maxOutputTokens: 8_000,
      contextWindow: 200_000,
      temperature: 0,
    },
  ],
  roo: [
    {
      name: "xai/grok-code-fast-1",
      displayName: "Grok Code Fast",
      description:
        "A reasoning model that is blazing fast and excels at agentic coding, accessible for free through Roo Code Cloud for a limited time.",
      maxOutputTokens: 16_384,
      contextWindow: 262_144,
      temperature: 0,
      dollarSigns: 0,
    },
    {
      name: "roo/code-supernova",
      displayName: "Code Supernova",
      description:
        "A versatile agentic coding stealth model that supports image inputs, accessible for free through Roo Code Cloud for a limited time.",
      maxOutputTokens: 16_384,
      contextWindow: 200_000,
      temperature: 0,
      dollarSigns: 0,
    },
  ],
};

export const TURBO_MODELS: LanguageModel[] = [
  {
    apiName: "qwen3-coder:turbo",
    displayName: "Qwen3 Coder",
    description: "Qwen's best coding model (very fast)",
    maxOutputTokens: 32_000,
    contextWindow: 131_000,
    temperature: 0,
    dollarSigns: 2,
    type: "cloud",
  },
  {
    apiName: "kimi-k2:turbo",
    displayName: "Kimi K2",
    description: "Kimi 0905 update (fast)",
    maxOutputTokens: 16_000,
    contextWindow: 256_000,
    temperature: 0,
    dollarSigns: 2,
    type: "cloud",
  },
];

export const FREE_OPENROUTER_MODEL_NAMES = MODEL_OPTIONS.openrouter
  .filter((model) => model.name.endsWith(":free"))
  .map((model) => model.name);

export const PROVIDER_TO_ENV_VAR: Record<string, string> = {
  openai: "OPENAI_API_KEY",
  anthropic: "ANTHROPIC_API_KEY",
  google: "GEMINI_API_KEY",
  openrouter: "OPENROUTER_API_KEY",
  azure: "AZURE_API_KEY",
  xai: "XAI_API_KEY",
  nvidia: "NVIDIA_API_KEY",
  bedrock: "AWS_BEARER_TOKEN_BEDROCK",
};

export const CLOUD_PROVIDERS: Record<
  string,
  {
    displayName: string;
    hasFreeTier?: boolean;
    websiteUrl?: string;
    gatewayPrefix?: string;
    secondary?: boolean;
  }
> = {
  openai: {
    displayName: "OpenAI",
    hasFreeTier: false,
    websiteUrl: "https://platform.openai.com/api-keys",
    gatewayPrefix: "",
  },
  anthropic: {
    displayName: "Anthropic",
    hasFreeTier: false,
    websiteUrl: "https://console.anthropic.com/settings/keys",
    gatewayPrefix: "anthropic/",
  },
  google: {
    displayName: "Google",
    hasFreeTier: true,
    websiteUrl: "https://aistudio.google.com/app/apikey",
    gatewayPrefix: "gemini/",
  },
  vertex: {
    displayName: "Google Vertex AI",
    hasFreeTier: false,
    websiteUrl: "https://console.cloud.google.com/vertex-ai",
    // Use the same gateway prefix as Google Gemini for AliFullStack Pro compatibility.
    gatewayPrefix: "gemini/",
    secondary: true,
  },
  openrouter: {
    displayName: "OpenRouter",
    hasFreeTier: true,
    websiteUrl: "https://openrouter.ai/settings/keys",
    gatewayPrefix: "openrouter/",
  },
  auto: {
    displayName: "AliFullStack",
    websiteUrl: "https://academy.alifullstack.alitech.io/settings",
    gatewayPrefix: "alifullstack/",
  },
  azure: {
    displayName: "Azure OpenAI",
    hasFreeTier: false,
    websiteUrl: "https://portal.azure.com/",
    gatewayPrefix: "",
    secondary: true,
  },
  xai: {
    displayName: "xAI",
    hasFreeTier: false,
    websiteUrl: "https://console.x.ai/",
    gatewayPrefix: "xai/",
    secondary: true,
  },
  nvidia: {
    displayName: "NVIDIA NIM",
    hasFreeTier: false,
    websiteUrl: "https://build.nvidia.com/",
    // NVIDIA uses a direct OpenAI-compatible endpoint (not through AliFullStack Pro gateway).
    // Setting gatewayPrefix to undefined ensures the Pro gateway skip logic works
    // and the direct client in get_model_client.ts is used instead.
    gatewayPrefix: undefined,
  },
  bedrock: {
    displayName: "AWS Bedrock",
    hasFreeTier: false,
    websiteUrl: "https://console.aws.amazon.com/bedrock/",
    gatewayPrefix: "bedrock/",
    secondary: true,
  },
  roo: {
    displayName: "Roo Code Cloud",
    hasFreeTier: true,
    websiteUrl: "https://roocode.com",
    gatewayPrefix: "roo/",
  },
};

export const LOCAL_PROVIDERS: Record<
  string,
  {
    displayName: string;
    hasFreeTier: boolean;
  }
> = {
  ollama: {
    displayName: "Ollama",
    hasFreeTier: true,
  },
  lmstudio: {
    displayName: "LM Studio",
    hasFreeTier: true,
  },
};
